- name: show facts
  hosts: all
  tasks:
    - name: print facts
      debug:
        var: ansible_facts

    - name: debug deneme
      shell: "ls -al"
      register: result

    - name: display output 
      debug:
        var: result.stdout_lines

    - name: display output v2 
      debug:
        msg: "{{ result.stdout_lines }}"    